### ISSUE TITLE
Replace SLF4j logger with standard Spring logger

### ISSUE THREAD

**Issue by tomwetjens** [shapeshifter/shapeshifter-library#28]
As Spring uses Commons Logging internally, it is already pulled in as a dependency. So why not use that and have one dependency less?

`@Slf4j` can become `@CommonsLog` and pretty much everything else can remain the same.

Or where not using Lombok:
`Logger.getLogger(...)` becomes `LogFactory.getLog(...)`

**Comment by tomwetjens** [comment]
Now we have split into non-Spring and Spring modules... what logging framework would make sense if not using Spring?

**Comment by eelcodenheijer** [comment]
|Old | New|
-----------
|@Slf4j| @CommonsLog|
